### ISSUE TITLE
Steam not reflecting changed collections

### ISSUE THREAD

**Issue by slcc2c** [Depressurizer/Depressurizer#231] opened 2022-01-30 07:44 UTC
On 5.2 steam is no longer reflecting saved changes.

**Comment by mvegter** [comment] 2022-01-30 13:02
Duplicate of #219

**Closed as completed by mvegter** 2022-01-30 13:02 UTC
Labels: Type: Invalid

**Comment by slcc2c** [comment] 2022-01-30 15:33
> Duplicate of #219 

I am having a different issue than reported in #219. Everything appears fine in the UI but nothing saves to steam. I have used the tools for years but recently moved to 5.*.

**Comment by slcc2c** [comment] 2022-02-02 03:38
@mvegter hey if you wouldn't mind hearing me out, this is a different issue than the bug that you linked. What other documentation or explanation do you need?
