### ISSUE TITLE
Categories list disappears on resize

### ISSUE THREAD

**Issue by DrDoctor13** [Depressurizer/Depressurizer#43] opened 2018-06-26 18:29 UTC
**Describe the bug**
After resizing the window, every entry in the categories list disappears until they are individually clicked on

**To Reproduce**
1. Open program
2. Resize window
3. See error

**Expected behavior**
The list of categories do not disappear

**Screenshots**
![capture](https://user-images.githubusercontent.com/11695921/41931870-564fdbbe-794d-11e8-8eff-b350d3d11779.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 8.1

**Comment by mvegter** [comment] 2018-07-01 20:14
@DrDoctor13 I can't reproduce this error. This could be fixed in the latest release, [Depressurizer v3.0.0](https://github.com/mvegter/Depressurizer/releases/tag/v3.0.0). Could you check if this still happens?

**Comment by mvegter** [comment] 2018-07-08 20:37
@DrDoctor13 Closing this due to inactivity.

**Closed as completed** 2018-07-08 20:37 UTC
Labels: Type: Bug
