### ISSUE TITLE
Alphabeticising is not the same as Steam's

### ISSUE THREAD

**Issue by haboutnnah** [Depressurizer/Depressurizer#99] opened 2018-12-23 03:26 UTC
**Describe the bug**
Some things are ordered differently to steam

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a tag that starts with `(+` and another that starts with `(-`, and populate it with at least one game 
2. Save the tag to Steam.
3. Notice the difference between the order in Steam and that in Depressuriser.

**Expected behavior**
Same order as Steam

**Screenshots**
![Screenshot showing how + is higher in Steam but - is higher in Depressurizer](https://i.imgur.com/lMJ29Rn.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version 1809
 -  .NET Version 4.7.2

![.Net versions](https://i.imgur.com/ZLJYYP5.png)

Specs: 

![Specs](https://i.imgur.com/ETsMA1Y.png)

**Additional context**
Similar to #65

**Comment by mvegter** [comment] 2018-12-24 10:16
Closing this issue as it is a duplicate of #65, feel free to post any information in that issue.

**Closed as completed by mvegter** 2018-12-24 10:16 UTC
