### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by slcc2c** [Depressurizer/Depressurizer#232] opened 2022-02-05 14:28 UTC
**Describe the bug**

**To Reproduce**
1. Click Autocategorize
2. Save profile to steam

**Expected behavior**
I expected my categories to be saved to steam. As you can see in the screenshots, they are not saved. 

**Screenshots**
<img width="187" alt="Screenshot 2022-02-05 082045" src="https://user-images.githubusercontent.com/11946869/152645688-648ef38d-934a-4fef-9d6d-179654b883ab.png">
<img width="1168" alt="Screenshot 2022-02-05 082940" src="https://user-images.githubusercontent.com/11946869/152645926-bf161a8b-a7b6-418c-b501-1c44aa8ffe81.png">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 5.2
 -  .NET Version 4.8.04161

**Additional context**
I have been using Depressurizer since version 0.7.4.2 and have never had this issue before.

**Comment by mvegter** [comment] 2022-02-05 15:02
Duplicate of https://github.com/Depressurizer/Depressurizer/issues/219

**Closed as completed by mvegter** 2022-02-05 15:02 UTC
Labels: Type: Invalid

**Comment by slcc2c** [comment] 2022-02-05 15:19
@mvegter its not a duplicate, my issue is with the opposite direction. I am having issues exporting,not importing.
