### ISSUE TITLE
consistent crash when right clicking the column header "tags"

### ISSUE THREAD

**Issue by vaendryl** [Depressurizer/Depressurizer#91] opened 2018-12-12 11:02 UTC
**Describe the bug**
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Depressurizer.FormMain.<>c.<InitializeLstGames>b__108_6(Object g)
   at BrightIdeasSoftware.OLVColumn.GetValue(Object rowObject)
   at Depressurizer.CommaClusteringStrategy.GetClusterKey(Object model)
   at BrightIdeasSoftware.FilterMenuBuilder.ClusterOneModel(IClusteringStrategy strategy, NullableDictionary`2 map, Object model)
   at BrightIdeasSoftware.FilterMenuBuilder.Cluster(IClusteringStrategy strategy, ObjectListView listView, OLVColumn column)
   at BrightIdeasSoftware.FilterMenuBuilder.MakeFilterMenu(ToolStripDropDown strip, ObjectListView listView, OLVColumn column)
   at BrightIdeasSoftware.ObjectListView.MakeFilteringMenu(ToolStripDropDown strip, Int32 columnIndex)
   at BrightIdeasSoftware.ObjectListView.MakeHeaderRightClickMenu(Int32 columnIndex)
   at BrightIdeasSoftware.ObjectListView.ShowHeaderRightClickMenu(Int32 columnIndex, Point pt)
   at BrightIdeasSoftware.ObjectListView.HandleHeaderRightClick(Int32 columnIndex)
   at BrightIdeasSoftware.ObjectListView.HandleContextMenu(Message& m)
   at BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**To Reproduce**
launch program. right click column headers

**Expected behavior**
I expected a popup where I can choose different headers

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/6646905/49865620-c056b680-fe05-11e8-8841-de92a95d4e4a.png)

**Desktop (please complete the following information):**
running windows 10

**Additional context**
tags column seems empty for all entries

**Comment by mvegter** [comment] 2018-12-12 15:36
I'm assuming this is a duplicate of #90. If this is still present in the latest release, please feel free to create a new issue with up-to-date information.

**Closed as completed by mvegter** 2018-12-12 15:36 UTC
