### ISSUE TITLE
Version 3 defaults to Dutch language

### ISSUE THREAD

**Issue by Quitch** [Depressurizer/Depressurizer#49] opened 2018-07-05 09:04 UTC
**Describe the bug**
All translated text is displayed in Dutch on a new install

**To Reproduce**
1. Download version 3.0
2. Run version 3.0

**Expected behavior**
Program defaults to English

**Desktop (please complete the following information):**
 - Windows 10 Pro x64
 - Chrome
 - Version 67.0.3396.99 (Official Build) (64-bit)

**Additional context**
Able to change language back to English once program loads. Nerderlands appears at the top of the language list.

**Comment by derekslenk** [comment] 2018-07-06 00:46
Another issue I found - after you change it back to English, most things change except the default categories. "Bij Genre, Bij Jaar, etc..."
![image](https://user-images.githubusercontent.com/42957/42354379-6ae025e0-8094-11e8-9f66-da5f7062fbda.png)

**Comment by Quitch** [comment] 2018-07-06 07:39
@derekslenk see #47 and #50

**Comment by mvegter** [comment] 2018-07-08 20:30
Closing this as a duplicate of #47 and #50

**Closed as completed by mvegter** 2018-07-08 20:30 UTC
